plugins {
    id 'java'
    id 'idea'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'idea'
    apply plugin: 'maven-publish'

    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
        mavenCentral()
    }

    version = project.name == 'fabric'
        ? "${rootProject.mod_version}+fabric${rootProject.mod_version_minecraft_suffix}"
        : project.name == 'neoforge'
            ? "${rootProject.mod_version}+neoforge${rootProject.mod_version_minecraft_suffix}"
            : rootProject.mod_version
    group = rootProject.maven_group

    base {
        archivesName = rootProject.archives_base_name
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    java {
        withSourcesJar()
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
    }

    tasks.withType(Jar).configureEach {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}

tasks.named('jar') {
    enabled = false
}
