plugins {
    id 'fabric-loom' version "${loom_version}"
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.officialMojangMappings()
    compileOnly 'io.github.llamalad7:mixinextras-common:0.3.5'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.5'
    compileOnly 'net.fabricmc:sponge-mixin:0.15.3+mixin.0.8.7'
}

loom {
    mixin.useLegacyMixinAp = false
}

tasks.named('jar') {
    enabled = false
}

tasks.named('remapJar') {
    enabled = false
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.archives_base_name
            from components.java
        }
    }
}
